title: Biologie
description: > # this means to ignore newlines until "baseurl:"
  Acesta este un site făcut special pentru o serie de proiecte pentru niște ore de biologie.
permalink: ':title/'
baseurl: "/biology" # the subpath of your site, e.g. /blog
url: "https://theqwerdev.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Proiecte Biologie # add your name
author-img: site_icon.png # add your photo
social-github: "TheQwerDev/biology" # add your Github handle

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
