title: Biologie
description: > # this means to ignore newlines until "baseurl:"
  Acesta este un site făcut special pentru o serie de proiecte pentru niște ore de biologie.
permalink: ':title/'
baseurl: "/biology" # the subpath of your site, e.g. /blog
url: "https://theqwerdev.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: me # add your name
author-img: gastrita.jpg # add your photo
about-author: oh god the pain # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: TheQwerDev # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - wdm
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
