title: Biologie
description: > # this means to ignore newlines until "baseurl:"
  Acesta este un site făcut special pentru o serie de proiecte pentru niște ore de biologie.
permalink: ':title/'
baseurl: "/biology" # the subpath of your site, e.g. /blog
url: "https://theqwerdev.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: me # add your name
author-img: gastrita.jpg # add your photo
about-author: "Acesta este un site pentru toate proiectele la bio făcute de către \n 
  Beșu-Roca Andrei \n 
  Pavelescu Andrei \n
  Brașoveanu Bogdan \n
  Enache Vlad \n
  Horodniceanu Ștefan \n
  Vasilache Mihai \n
  Cadăr Tudor" # add description
social-github: "TheQwerDev/biology" # add your Github handle


# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
